In [1]:
import numpy as np
import pandas as pd
import itertools

In [13]:
# ref.https://blog.csdn.net/DeniuHe/article/details/103102294

def train_validation_split(data, k):
    number_of_rows = data.shape[0]
    number_of_test = int(np.floor(number_of_rows / k))
    list_of_data_index = [i for i in range(number_of_rows)]
    
    result = pd.DataFrame(columns=['train_index','validation_index'], index=[i for i in range(k)])
    
    for i in range(k):
        total_index = np.array([i for i in range(number_of_rows)])
        test_index = np.random.choice(list_of_data_index, size=number_of_test, replace=False)
        train_index = np.delete(total_index, test_index)
        
        for index in test_index:
            list_of_data_index.remove(index)
        
        # print("{0}th iteration:\n".format({i}), "test index\n", test_index, "\ntrain index\n", train_index)
        
        result.iloc[i,0] = np.sort(train_index)
        result.iloc[i,1] = np.sort(test_index)

    return result

In [15]:
data = pd.read_csv("train.csv")
train_validation_split(data, 10)

,train_index,test_index
0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[17, 19, 35, 42, 48, 53, 56, 62, 85, 89, 100, ..."
1,"[0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14...","[8, 21, 26, 41, 50, 66, 68, 70, 79, 91, 92, 95..."
2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[22, 36, 47, 65, 76, 87, 110, 122, 133, 150, 1..."
3,"[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 13, 14, 15, 16...","[5, 11, 12, 25, 28, 37, 44, 54, 61, 64, 72, 80..."
4,"[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[1, 23, 29, 30, 33, 38, 39, 63, 106, 114, 116,..."
5,"[0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15...","[3, 13, 18, 31, 32, 40, 55, 57, 90, 102, 108, ..."
6,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[0, 20, 43, 52, 74, 75, 86, 88, 96, 99, 115, 1..."
7,"[0, 1, 2, 3, 4, 5, 8, 10, 11, 12, 13, 14, 15, ...","[6, 7, 9, 27, 34, 58, 60, 67, 69, 71, 77, 82, ..."
8,"[0, 1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 13, 17, 18...","[4, 10, 14, 15, 16, 45, 97, 98, 101, 121, 134,..."
9,"[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[2, 24, 46, 49, 51, 59, 73, 78, 84, 93, 124, 1..."

In [11]:
def combination_grid(parameters):
    '''
    parameters: a dictionary, e.g. parameters = {'max_depth':[3, 5, 7, 9], 'min_samples_leaf': [1, 2, 3, 4]}
    '''
    # https://www.codegrepper.com/code-examples/delphi/python+list+of+lists+all+combinations
    combinations = list(itertools.product(*list(parameters.values())))
    df = pd.DataFrame(combinations, columns = parameters.keys()) 
    
    return df

In [12]:
parameters = {'max_depth':[3, 5, 7, 9], 'min_samples_leaf': [1, 2, 3, 4]}
combination_grid(parameters)

    max_depth  min_samples_leaf
0           3                 1
1           3                 2
2           3                 3
3           3                 4
4           5                 1
5           5                 2
6           5                 3
7           5                 4
8           7                 1
9           7                 2
10          7                 3
11          7                 4
12          9                 1
13          9                 2
14          9                 3
15          9                 4